#pragma once

#include <ArduboyTones.h>

#include "song_bpms.h"
#include "song_lengths.h"
#include "song_scores.h"
#include "song_titles.h"
#include "tracks.h"
#include "FlashStringHelper.h"

#define TRACK_GAP 500

const int8_t SONGS_COUNT = sizeof(TRACKS) / sizeof(int8_t);

enum Stage
{
  Intro,
  Operation
};

enum Volume
{
  Mute,
  Low,
  High
};

struct State
{
  Stage stage;

  int8_t trackIndex;
  uint32_t eventStarted;

  Volume volume;

  bool isPlaying;
};

struct Song
{
  const char *title;
  const uint16_t *score;
  uint16_t length;
  uint16_t beatsPerMinute;
};

// TODO: generate with ./compile_songs.sh
const Song songs[]{
    {ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE,
     ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_SCORE,
     ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_LENGTH,
     ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM},
    {BABY_SKIN_TITLE,
     BABY_SKIN_SCORE,
     BABY_SKIN_LENGTH,
     BABY_SKIN_BPM},
    {BOUNCING_A_BALL_TITLE,
     BOUNCING_A_BALL_SCORE,
     BOUNCING_A_BALL_LENGTH,
     BOUNCING_A_BALL_BPM},
    {BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_TITLE,
     BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_SCORE,
     BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_LENGTH,
     BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_BPM},
    {BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_TITLE,
     BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_SCORE,
     BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_LENGTH,
     BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_BPM},
    {DADA_DO_TITLE,
     DADA_DO_SCORE,
     DADA_DO_LENGTH,
     DADA_DO_BPM},
    {GETTING_PAPA_SOME_COFFEE_TITLE,
     GETTING_PAPA_SOME_COFFEE_SCORE,
     GETTING_PAPA_SOME_COFFEE_LENGTH,
     GETTING_PAPA_SOME_COFFEE_BPM},
    {GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_TITLE,
     GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_SCORE,
     GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_LENGTH,
     GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_BPM},
    {I_GOT_A_ROCK_IN_MY_POCKET_TITLE,
     I_GOT_A_ROCK_IN_MY_POCKET_SCORE,
     I_GOT_A_ROCK_IN_MY_POCKET_LENGTH,
     I_GOT_A_ROCK_IN_MY_POCKET_BPM},
    {I_MAKE_A_LITTLE_TACO_TITLE,
     I_MAKE_A_LITTLE_TACO_SCORE,
     I_MAKE_A_LITTLE_TACO_LENGTH,
     I_MAKE_A_LITTLE_TACO_BPM},
    {I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_TITLE,
     I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_SCORE,
     I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_LENGTH,
     I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_BPM},
    {LETS_GO_PEE_WITH_DAD_TITLE,
     LETS_GO_PEE_WITH_DAD_SCORE,
     LETS_GO_PEE_WITH_DAD_LENGTH,
     LETS_GO_PEE_WITH_DAD_BPM},
    {MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_TITLE,
     MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_SCORE,
     MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_LENGTH,
     MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_BPM},
    {MY_BABY_IS_A_PUNCHING_MACHINE_TITLE,
     MY_BABY_IS_A_PUNCHING_MACHINE_SCORE,
     MY_BABY_IS_A_PUNCHING_MACHINE_LENGTH,
     MY_BABY_IS_A_PUNCHING_MACHINE_BPM},
    {MY_BABY_LOVES_TO_GO_POOPY_TITLE,
     MY_BABY_LOVES_TO_GO_POOPY_SCORE,
     MY_BABY_LOVES_TO_GO_POOPY_LENGTH,
     MY_BABY_LOVES_TO_GO_POOPY_BPM},
    {ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_TITLE,
     ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_SCORE,
     ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_LENGTH,
     ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_BPM},
    {POOP_STUCK_TO_A_BUTT_TITLE,
     POOP_STUCK_TO_A_BUTT_SCORE,
     POOP_STUCK_TO_A_BUTT_LENGTH,
     POOP_STUCK_TO_A_BUTT_BPM},
    {PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_TITLE,
     PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_SCORE,
     PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_LENGTH,
     PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_BPM},
    {STREET_SWEEPER_TITLE,
     STREET_SWEEPER_SCORE,
     STREET_SWEEPER_LENGTH,
     STREET_SWEEPER_BPM},
    {THATS_HOW_YOU_SPELL_MAMA_TITLE,
     THATS_HOW_YOU_SPELL_MAMA_SCORE,
     THATS_HOW_YOU_SPELL_MAMA_LENGTH,
     THATS_HOW_YOU_SPELL_MAMA_BPM},
    {THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE,
     THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_SCORE,
     THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_LENGTH,
     THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM},
    {WASHING_YOUR_FACE_TITLE,
     WASHING_YOUR_FACE_SCORE,
     WASHING_YOUR_FACE_LENGTH,
     WASHING_YOUR_FACE_BPM},
    {WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE,
     WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_SCORE,
     WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_LENGTH,
     WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM},
    {WERE_ALMOST_HOME_TITLE,
     WERE_ALMOST_HOME_SCORE,
     WERE_ALMOST_HOME_LENGTH,
     WERE_ALMOST_HOME_BPM},
    {WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_TITLE,
     WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_SCORE,
     WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_LENGTH,
     WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_BPM},
    {WHOS_MY_LITTLE_BABY_BIRD_TITLE,
     WHOS_MY_LITTLE_BABY_BIRD_SCORE,
     WHOS_MY_LITTLE_BABY_BIRD_LENGTH,
     WHOS_MY_LITTLE_BABY_BIRD_BPM},
    {WHOS_MY_LITTLE_DAIKINI_BABY_TITLE,
     WHOS_MY_LITTLE_DAIKINI_BABY_SCORE,
     WHOS_MY_LITTLE_DAIKINI_BABY_LENGTH,
     WHOS_MY_LITTLE_DAIKINI_BABY_BPM},
};