#pragma once

const char ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE[] PROGMEM =
  "ANY KIND OF\nCAR AND ANY\nKIND OF TRUCK\n(ANY KIND OF\nANY CAR\nAND TRUCK)";
const char GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_TITLE[] PROGMEM =
  "GUY IN A\nCOP CAR\nRUNNING A\nRED LIGHT";
const char I_MAKE_A_LITTLE_TACO_TITLE[] PROGMEM =
  "I MAKE A\nLITTLE TACO";
const char LETS_GO_PEE_WITH_DAD_TITLE[] PROGMEM =
  "LET'S GO PEE\nWITH DAD";
const char MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_TITLE[] PROGMEM =
  "MR. STANDING\n(WHO'S MY\nLITTLE\nSTANDING BOY)";
const char MY_BABY_IS_A_PUNCHING_MACHINE_TITLE[] PROGMEM =
"MY BABY IS\nA PUNCHING\nMACHINE";
const char MY_BABY_LOVES_TO_GO_POOPY_TITLE[] PROGMEM =
  "MY BABY\nLOVES TO\nGO POOPY";
const char STREET_SWEEPER_TITLE[] PROGMEM =
  "STREET\nSWEEPER";
const char THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE[] PROGMEM =
  "THIS TOWN'S\nGOT A LOT OF\nCONSTRUCTION";
const char WASHING_YOUR_FACE_TITLE[] PROGMEM =
  "WASHING\nYOUR FACE";
const char WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE[] PROGMEM =
  "WE ARE\nDRESSING UP\nAS A FAMILY\nOF SKELETONS";
const char WERE_ALMOST_HOME_TITLE[] PROGMEM =
  "WE'RE\nALMOST HOME";
const char WHOS_MY_LITTLE_BABY_BIRD_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE BABY\nBIRD";
const char WHOS_MY_LITTLE_DAIKINI_BABY_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE\nDAIKINI BABY";

// NOTE: must be alphabetically ordered
const char * const SONG_TITLES[] PROGMEM = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE,
  GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_TITLE,
  I_MAKE_A_LITTLE_TACO_TITLE,
  LETS_GO_PEE_WITH_DAD_TITLE,
  MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_TITLE,
  MY_BABY_IS_A_PUNCHING_MACHINE_TITLE,
  MY_BABY_LOVES_TO_GO_POOPY_TITLE,
  STREET_SWEEPER_TITLE,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE,
  WASHING_YOUR_FACE_TITLE,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE,
  WERE_ALMOST_HOME_TITLE,
  WHOS_MY_LITTLE_BABY_BIRD_TITLE,
  WHOS_MY_LITTLE_DAIKINI_BABY_TITLE,
};
