#pragma once

// Generated by ./compile_songs.sh
// Don't edit manually!

// clang-format off

const uint16_t anyKindOfCarAndAnyKindOfTruckLength = 3810;
const uint16_t babySkinLength = 15500;
const uint16_t bouncingABallLength = 14048;
const uint16_t bubblesBubblesWhosGotTheBubblesLength = 9126;
const uint16_t byeByeBubblesByeByeBathwaterLength = 14283;
const uint16_t dadaDoLength = 10701;
const uint16_t gettingPapaSomeCoffeeLength = 5805;
const uint16_t guyInACopCarRunningARedLightLength = 7141;
const uint16_t iGotARockInMyPocketLength = 6683;
const uint16_t iMakeALittleTacoLength = 9526;
const uint16_t iThinkALotAboutRinsingThatCoffeePotLength = 6670;
const uint16_t letsGoPeeWithDadLength = 11977;
const uint16_t mrStandingWhosMyLittleStandingBoyLength = 13815;
const uint16_t myBabyIsAPunchingMachineLength = 13750;
const uint16_t myBabyLovesToGoPoopyLength = 7750;
const uint16_t oneTwoThreeFourFiveSixSevenEightNineTenLength = 3809;
const uint16_t poopStuckToAButtLength = 7892;
const uint16_t puttingOnYourPantsLikeABigBoyLength = 9150;
const uint16_t streetSweeperLength = 5070;
const uint16_t thatsHowYouSpellMamaLength = 15496;
const uint16_t thisTownsGotALotOfConstructionLength = 6910;
const uint16_t washingYourFaceLength = 7250;
const uint16_t weAreDressingUpAsAFamilyOfSkeletonsLength = 8196;
const uint16_t wereAlmostHomeLength = 13250;
const uint16_t whenYoureDoneWithYourHamYouThrowItOnTheGroundLength = 11635;
const uint16_t whosMyLittleBabyBirdLength = 8639;
const uint16_t whosMyLittleDaikiniBabyLength = 11807;

const uint16_t songLengths[] = {
    anyKindOfCarAndAnyKindOfTruckLength,
    babySkinLength,
    bouncingABallLength,
    bubblesBubblesWhosGotTheBubblesLength,
    byeByeBubblesByeByeBathwaterLength,
    dadaDoLength,
    gettingPapaSomeCoffeeLength,
    guyInACopCarRunningARedLightLength,
    iGotARockInMyPocketLength,
    iMakeALittleTacoLength,
    iThinkALotAboutRinsingThatCoffeePotLength,
    letsGoPeeWithDadLength,
    mrStandingWhosMyLittleStandingBoyLength,
    myBabyIsAPunchingMachineLength,
    myBabyLovesToGoPoopyLength,
    oneTwoThreeFourFiveSixSevenEightNineTenLength,
    poopStuckToAButtLength,
    puttingOnYourPantsLikeABigBoyLength,
    streetSweeperLength,
    thatsHowYouSpellMamaLength,
    thisTownsGotALotOfConstructionLength,
    washingYourFaceLength,
    weAreDressingUpAsAFamilyOfSkeletonsLength,
    wereAlmostHomeLength,
    whenYoureDoneWithYourHamYouThrowItOnTheGroundLength,
    whosMyLittleBabyBirdLength,
    whosMyLittleDaikiniBabyLength,
};

const uint8_t anyKindOfCarAndAnyKindOfTruck = 0;
const uint8_t babySkin = 1;
const uint8_t bouncingABall = 2;
const uint8_t bubblesBubblesWhosGotTheBubbles = 3;
const uint8_t byeByeBubblesByeByeBathwater = 4;
const uint8_t dadaDo = 5;
const uint8_t gettingPapaSomeCoffee = 6;
const uint8_t guyInACopCarRunningARedLight = 7;
const uint8_t iGotARockInMyPocket = 8;
const uint8_t iMakeALittleTaco = 9;
const uint8_t iThinkALotAboutRinsingThatCoffeePot = 10;
const uint8_t letsGoPeeWithDad = 11;
const uint8_t mrStandingWhosMyLittleStandingBoy = 12;
const uint8_t myBabyIsAPunchingMachine = 13;
const uint8_t myBabyLovesToGoPoopy = 14;
const uint8_t oneTwoThreeFourFiveSixSevenEightNineTen = 15;
const uint8_t poopStuckToAButt = 16;
const uint8_t puttingOnYourPantsLikeABigBoy = 17;
const uint8_t streetSweeper = 18;
const uint8_t thatsHowYouSpellMama = 19;
const uint8_t thisTownsGotALotOfConstruction = 20;
const uint8_t washingYourFace = 21;
const uint8_t weAreDressingUpAsAFamilyOfSkeletons = 22;
const uint8_t wereAlmostHome = 23;
const uint8_t whenYoureDoneWithYourHamYouThrowItOnTheGround = 24;
const uint8_t whosMyLittleBabyBird = 25;
const uint8_t whosMyLittleDaikiniBaby = 26;
