#pragma once

const uint16_t ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM = 110;
const uint16_t GETTING_PAPA_SOME_COFFEE_BPM = 160;
const uint16_t GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_BPM = 130;
const uint16_t I_MAKE_A_LITTLE_TACO_BPM = 110;
const uint16_t LETS_GO_PEE_WITH_DAD_BPM = 120;
const uint16_t MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_BPM = 130;
const uint16_t MY_BABY_IS_A_PUNCHING_MACHINE_BPM = 120;
const uint16_t MY_BABY_LOVES_TO_GO_POOPY_BPM = 120;
const uint16_t STREET_SWEEPER_BPM = 130;
const uint16_t THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM = 130;
const uint16_t WASHING_YOUR_FACE_BPM = 120;
const uint16_t WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM = 115;
const uint16_t WERE_ALMOST_HOME_BPM = 120;
const uint16_t WHOS_MY_LITTLE_BABY_BIRD_BPM = 110;
const uint16_t WHOS_MY_LITTLE_DAIKINI_BABY_BPM = 80;

// NOTE: must be alphabetically ordered
const uint16_t SONG_BPMS[] = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM,
  GETTING_PAPA_SOME_COFFEE_BPM,
  GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_BPM,
  I_MAKE_A_LITTLE_TACO_BPM,
  LETS_GO_PEE_WITH_DAD_BPM,
  MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_BPM,
  MY_BABY_IS_A_PUNCHING_MACHINE_BPM,
  MY_BABY_LOVES_TO_GO_POOPY_BPM,
  STREET_SWEEPER_BPM,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM,
  WASHING_YOUR_FACE_BPM,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM,
  WERE_ALMOST_HOME_BPM,
  WHOS_MY_LITTLE_BABY_BIRD_BPM,
  WHOS_MY_LITTLE_DAIKINI_BABY_BPM,
};