#pragma once

const char ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE[] PROGMEM =
  "ANY KIND OF\nCAR AND ANY\nKIND OF TRUCK";
const char I_MAKE_A_LITTLE_TACO_TITLE[] PROGMEM =
  "I MAKE\nA LITTLE\nTACO";
const char MY_BABY_LOVES_TO_GO_POOPY_TITLE[] PROGMEM =
  "MY BABY\nLOVES TO GO\nPOOPY";
const char THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE[] PROGMEM =
  "THIS TOWN'S\nGOT A LOT OF\nCONSTRUCTION";
const char WASHING_YOUR_FACE_TITLE[] PROGMEM =
  "WASHING\nYOUR FACE";
const char WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE[] PROGMEM =
  "WE ARE\nDRESSING UP\nAS A FAMILY\nOF SKELETONS";
const char WERE_ALMOST_HOME_TITLE[] PROGMEM =
  "WE'RE ALMOST\nHOME";
const char WHOS_MY_LITTLE_BABY_BIRD_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE BABY\nBIRD";
const char WHOS_MY_LITTLE_DAIKINI_BABY_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE DAIKINI\nBABY";

// NOTE: must be alphabetically ordered like lengths and scores
const char * const SONG_TITLES[] PROGMEM = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE,
  I_MAKE_A_LITTLE_TACO_TITLE,
  MY_BABY_LOVES_TO_GO_POOPY_TITLE,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE,
  WASHING_YOUR_FACE_TITLE,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE,
  WERE_ALMOST_HOME_TITLE,
  WHOS_MY_LITTLE_BABY_BIRD_TITLE,
  WHOS_MY_LITTLE_DAIKINI_BABY_TITLE,
};