#pragma once

const int16_t ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM = 110;
const int16_t I_MAKE_A_LITTLE_TACO_BPM = 110;
const int16_t MY_BABY_LOVES_TO_GO_POOPY_BPM = 120;
const int16_t THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM = 130;
const int16_t WASHING_YOUR_FACE_BPM = 120;
const int16_t WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM = 115;
const int16_t WERE_ALMOST_HOME_BPM = 120;
const int16_t WHOS_MY_LITTLE_BABY_BIRD_BPM = 110;
const int16_t WHOS_MY_LITTLE_DAIKINI_BABY_BPM = 80;

// NOTE: must be alphabetically ordered
const int16_t SONG_BPMS[] = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM,
  I_MAKE_A_LITTLE_TACO_BPM,
  MY_BABY_LOVES_TO_GO_POOPY_BPM,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM,
  WASHING_YOUR_FACE_BPM,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM,
  WERE_ALMOST_HOME_BPM,
  WHOS_MY_LITTLE_BABY_BIRD_BPM,
  WHOS_MY_LITTLE_DAIKINI_BABY_BPM,
};