#pragma once

const uint16_t ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM = 110;
const uint16_t BABY_SKIN_BPM = 120;
const uint16_t BOUNCING_A_BALL_BPM = 130;
const uint16_t BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_BPM = 95;
const uint16_t BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_BPM = 130;
const uint16_t DADA_DO_BPM = 140;
const uint16_t GETTING_PAPA_SOME_COFFEE_BPM = 80;
const uint16_t GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_BPM = 130;
const uint16_t I_GOT_A_ROCK_IN_MY_POCKET_BPM = 105;
const uint16_t I_MAKE_A_LITTLE_TACO_BPM = 110;
const uint16_t I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_BPM = 130;
const uint16_t LETS_GO_PEE_WITH_DAD_BPM = 145;
const uint16_t MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_BPM = 130;
const uint16_t MY_BABY_IS_A_PUNCHING_MACHINE_BPM = 120;
const uint16_t MY_BABY_LOVES_TO_GO_POOPY_BPM = 120;
const uint16_t ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_BPM = 110;
const uint16_t POOP_STUCK_TO_A_BUTT_BPM = 110;
const uint16_t PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_BPM = 100;
const uint16_t STREET_SWEEPER_BPM = 130;
const uint16_t THATS_HOW_YOU_SPELL_MAMA_BPM = 170;
const uint16_t THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM = 130;
const uint16_t WASHING_YOUR_FACE_BPM = 120;
const uint16_t WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM = 115;
const uint16_t WERE_ALMOST_HOME_BPM = 120;
const uint16_t WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_BPM = 90;
const uint16_t WHOS_MY_LITTLE_BABY_BIRD_BPM = 110;
const uint16_t WHOS_MY_LITTLE_DAIKINI_BABY_BPM = 80;

// NOTE: must be alphabetically ordered
const uint16_t SONG_BPMS[] = {
    ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM,
    BABY_SKIN_BPM,
    BOUNCING_A_BALL_BPM,
    BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_BPM,
    BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_BPM,
    DADA_DO_BPM,
    GETTING_PAPA_SOME_COFFEE_BPM,
    GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_BPM,
    I_GOT_A_ROCK_IN_MY_POCKET_BPM,
    I_MAKE_A_LITTLE_TACO_BPM,
    I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_BPM,
    LETS_GO_PEE_WITH_DAD_BPM,
    MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_BPM,
    MY_BABY_IS_A_PUNCHING_MACHINE_BPM,
    MY_BABY_LOVES_TO_GO_POOPY_BPM,
    ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_BPM,
    POOP_STUCK_TO_A_BUTT_BPM,
    PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_BPM,
    STREET_SWEEPER_BPM,
    THATS_HOW_YOU_SPELL_MAMA_BPM,
    THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM,
    WASHING_YOUR_FACE_BPM,
    WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM,
    WERE_ALMOST_HOME_BPM,
    WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_BPM,
    WHOS_MY_LITTLE_BABY_BIRD_BPM,
    WHOS_MY_LITTLE_DAIKINI_BABY_BPM,
};