#pragma once

// Generated by ./compile_songs.sh
// Don't edit manually!

// clang-format off

const uint16_t anyKindOfCarAndAnyKindOfTruckLength = 3810;
const uint16_t babySkinLength = 15500;
const uint16_t bouncingABallLength = 14048;
const uint16_t bubblesBubblesWhosGotTheBubblesLength = 9126;
const uint16_t byeByeBubblesByeByeBathwaterLength = 14283;
const uint16_t dadaDoLength = 10701;
const uint16_t gettingPapaSomeCoffeeLength = 5805;
const uint16_t guyInACopCarRunningARedLightLength = 7141;
const uint16_t iGotARockInMyPocketLength = 6683;
const uint16_t iMakeALittleTacoLength = 9526;
const uint16_t iThinkALotAboutRinsingThatCoffeePotLength = 6670;
const uint16_t letsGoPeeWithDadLength = 11977;
const uint16_t mrStandingWhosMyLittleStandingBoyLength = 13815;
const uint16_t myBabyIsAPunchingMachineLength = 13750;
const uint16_t myBabyLovesToGoPoopyLength = 7750;
const uint16_t oneTwoThreeFourFiveSixSevenEightNineTenLength = 3809;
const uint16_t poopStuckToAButtLength = 7892;
const uint16_t puttingOnYourPantsLikeABigBoyLength = 9150;
const uint16_t streetSweeperLength = 5070;
const uint16_t thatsHowYouSpellMamaLength = 15496;
const uint16_t thisTownsGotALotOfConstructionLength = 6910;
const uint16_t washingYourFaceLength = 7250;
const uint16_t weAreDressingUpAsAFamilyOfSkeletonsLength = 8196;
const uint16_t wereAlmostHomeLength = 13250;
const uint16_t whenYoureDoneWithYourHamYouThrowItOnTheGroundLength = 11635;
const uint16_t whosMyLittleBabyBirdLength = 8639;
const uint16_t whosMyLittleDaikiniBabyLength = 11807;

const uint16_t songLengths[] = {
    anyKindOfCarAndAnyKindOfTruckLength,
    babySkinLength,
    bouncingABallLength,
    bubblesBubblesWhosGotTheBubblesLength,
    byeByeBubblesByeByeBathwaterLength,
    dadaDoLength,
    gettingPapaSomeCoffeeLength,
    guyInACopCarRunningARedLightLength,
    iGotARockInMyPocketLength,
    iMakeALittleTacoLength,
    iThinkALotAboutRinsingThatCoffeePotLength,
    letsGoPeeWithDadLength,
    mrStandingWhosMyLittleStandingBoyLength,
    myBabyIsAPunchingMachineLength,
    myBabyLovesToGoPoopyLength,
    oneTwoThreeFourFiveSixSevenEightNineTenLength,
    poopStuckToAButtLength,
    puttingOnYourPantsLikeABigBoyLength,
    streetSweeperLength,
    thatsHowYouSpellMamaLength,
    thisTownsGotALotOfConstructionLength,
    washingYourFaceLength,
    weAreDressingUpAsAFamilyOfSkeletonsLength,
    wereAlmostHomeLength,
    whenYoureDoneWithYourHamYouThrowItOnTheGroundLength,
    whosMyLittleBabyBirdLength,
    whosMyLittleDaikiniBabyLength,
};

#define anyKindOfCarAndAnyKindOfTruck 0
#define babySkin 1
#define bouncingABall 2
#define bubblesBubblesWhosGotTheBubbles 3
#define byeByeBubblesByeByeBathwater 4
#define dadaDo 5
#define gettingPapaSomeCoffee 6
#define guyInACopCarRunningARedLight 7
#define iGotARockInMyPocket 8
#define iMakeALittleTaco 9
#define iThinkALotAboutRinsingThatCoffeePot 10
#define letsGoPeeWithDad 11
#define mrStandingWhosMyLittleStandingBoy 12
#define myBabyIsAPunchingMachine 13
#define myBabyLovesToGoPoopy 14
#define oneTwoThreeFourFiveSixSevenEightNineTen 15
#define poopStuckToAButt 16
#define puttingOnYourPantsLikeABigBoy 17
#define streetSweeper 18
#define thatsHowYouSpellMama 19
#define thisTownsGotALotOfConstruction 20
#define washingYourFace 21
#define weAreDressingUpAsAFamilyOfSkeletons 22
#define wereAlmostHome 23
#define whenYoureDoneWithYourHamYouThrowItOnTheGround 24
#define whosMyLittleBabyBird 25
#define whosMyLittleDaikiniBaby 26
