#pragma once

const char ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE[] PROGMEM =
  "ANY KIND OF\nCAR AND ANY\nKIND OF TRUCK\n(ANY KIND OF\nANY CAR\nAND TRUCK)";
const char BABY_SKIN_TITLE[] PROGMEM = "BABY SKIN";
const char BOUNCING_A_BALL_TITLE[] PROGMEM = "BOUNCING A\nBALL,\nBOUNCING A\nBOUNCY BALL";
const char BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_TITLE[] PROGMEM =
  "BUBBLES\nBUBBLES\n(WHO'S GOT\nTHE BUBBLES)";
const char BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_TITLE[] PROGMEM =
  "BYE BYE\nBUBBLES\nBYE BYE\nBATHWATER";
const char DADA_DO_TITLE[] PROGMEM = "DADA DO\n(MAMA MO)";
const char GETTING_PAPA_SOME_COFFEE_TITLE[] PROGMEM =
  "GETTING PAPA\nSOME COFFEE";
const char GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_TITLE[] PROGMEM =
  "GUY IN A\nCOP CAR\nRUNNING A\nRED LIGHT";
const char I_GOT_A_ROCK_IN_MY_POCKET_TITLE[] PROGMEM =
  "I GOT A ROCK\nIN MY POCKET";
const char I_MAKE_A_LITTLE_TACO_TITLE[] PROGMEM =
  "I MAKE A\nLITTLE TACO";
const char I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_TITLE[] PROGMEM =
  "I THINK\nA LOT ABOUT\nRINSING THAT\nCOFFEE POT";
const char LETS_GO_PEE_WITH_DAD_TITLE[] PROGMEM =
  "LET'S GO PEE\nWITH DAD";
const char MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_TITLE[] PROGMEM =
  "MR. STANDING\n(WHO'S MY\nLITTLE\nSTANDING BOY)";
const char MY_BABY_IS_A_PUNCHING_MACHINE_TITLE[] PROGMEM =
  "MY BABY IS\nA PUNCHING\nMACHINE!";
const char MY_BABY_LOVES_TO_GO_POOPY_TITLE[] PROGMEM =
  "MY BABY\nLOVES TO\nGO POOPY";
const char ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_TITLE[] PROGMEM =
  "ONE TWO THREE\nFOUR FIVE SIX\nSEVEN EIGHT\nNINE TEN";
const char POOP_STUCK_TO_A_BUTT_TITLE[] PROGMEM =
  "POOP STUCK\nTO A BUTT";
const char PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_TITLE[] PROGMEM =
  "PUTTING ON\nYOUR PANTS\nLIKE A\nBIG BOY";
const char STREET_SWEEPER_TITLE[] PROGMEM =
  "STREET\nSWEEPER";
const char THATS_HOW_YOU_SPELL_MAMA_TITLE[] PROGMEM =
  "(M A M A)\nTHAT'S HOW\nYOU SPELL\nMAMA";
const char THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE[] PROGMEM =
  "(WE BUILD IT\nUP AND THEN\nWE BUILD IT\nDOWN) THIS\nTOWN HAS GOT\nA LOT OF\nCONSTRUCTION";
const char WASHING_YOUR_FACE_TITLE[] PROGMEM =
  "WASHING\nYOUR FACE";
const char WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE[] PROGMEM =
  "WE ARE\nDRESSING UP\nAS A FAMILY\nOF SKELETONS";
const char WERE_ALMOST_HOME_TITLE[] PROGMEM =
  "WE'RE\nALMOST HOME";
const char WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_TITLE[] PROGMEM =
  "WHEN YOU'RE\nDONE WITH\nYOUR HAM\nYOU THROW IT\nON THE GROUND";
const char WHOS_MY_LITTLE_BABY_BIRD_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE BABY\nBIRD";
const char WHOS_MY_LITTLE_DAIKINI_BABY_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE\nDAIKINI BABY";

// NOTE: must be alphabetically ordered
const char * const SONG_TITLES[] PROGMEM = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE,
  BABY_SKIN_TITLE,
  BOUNCING_A_BALL_TITLE,
  BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES_TITLE,
  BYE_BYE_BUBBLES_BYE_BYE_BATHWATER_TITLE,
  DADA_DO_TITLE,
  GETTING_PAPA_SOME_COFFEE_TITLE,
  GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT_TITLE,
  I_GOT_A_ROCK_IN_MY_POCKET_TITLE,
  I_MAKE_A_LITTLE_TACO_TITLE,
  I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT_TITLE,
  LETS_GO_PEE_WITH_DAD_TITLE,
  MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY_TITLE,
  MY_BABY_IS_A_PUNCHING_MACHINE_TITLE,
  MY_BABY_LOVES_TO_GO_POOPY_TITLE,
  ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN_TITLE,
  POOP_STUCK_TO_A_BUTT_TITLE,
  PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY_TITLE,
  STREET_SWEEPER_TITLE,
  THATS_HOW_YOU_SPELL_MAMA_TITLE,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE,
  WASHING_YOUR_FACE_TITLE,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_TITLE,
  WERE_ALMOST_HOME_TITLE,
  WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND_TITLE,
  WHOS_MY_LITTLE_BABY_BIRD_TITLE,
  WHOS_MY_LITTLE_DAIKINI_BABY_TITLE,
};
