#pragma once

// Songs are songs; tracks are ordered songs
const int8_t TRACKS[] = {
  MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY,
  MY_BABY_IS_A_PUNCHING_MACHINE,
  GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS,
  WHOS_MY_LITTLE_BABY_BIRD,
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK,
  WERE_ALMOST_HOME,
  STREET_SWEEPER,
  MY_BABY_LOVES_TO_GO_POOPY,
  WASHING_YOUR_FACE,
  WHOS_MY_LITTLE_DAIKINI_BABY,
  I_MAKE_A_LITTLE_TACO,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION,
};