#pragma once

// Songs are songs; tracks are ordered songs
const int8_t TRACKS[] = {
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS,
  WHOS_MY_LITTLE_BABY_BIRD,
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK,
  WERE_ALMOST_HOME,
  MY_BABY_LOVES_TO_GO_POOPY,
  WASHING_YOUR_FACE,
  WHOS_MY_LITTLE_DAIKINI_BABY,
  I_MAKE_A_LITTLE_TACO,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION,
};

// TODO: extract
# define ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM 110
# define I_MAKE_A_LITTLE_TACO_BPM 110
# define MY_BABY_LOVES_TO_GO_POOPY_BPM 120
# define THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM 130
# define WASHING_YOUR_FACE_BPM 120
# define WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM 115
# define WERE_ALMOST_HOME_BPM 120
# define WHOS_MY_LITTLE_BABY_BIRD_BPM 110
# define WHOS_MY_LITTLE_DAIKINI_BABY_BPM 80

const int16_t SONG_BPMS[] = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_BPM,
  I_MAKE_A_LITTLE_TACO_BPM,
  MY_BABY_LOVES_TO_GO_POOPY_BPM,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_BPM,
  WASHING_YOUR_FACE_BPM,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS_BPM,
  WERE_ALMOST_HOME_BPM,
  WHOS_MY_LITTLE_BABY_BIRD_BPM,
  WHOS_MY_LITTLE_DAIKINI_BABY_BPM,
};