#pragma once

// Songs are songs; tracks are ordered songs
const int8_t TRACKS[] = {
  MY_BABY_IS_A_PUNCHING_MACHINE,
  GUY_IN_A_COP_CAR_RUNNING_A_RED_LIGHT,
  I_MAKE_A_LITTLE_TACO,
  GETTING_PAPA_SOME_COFFEE,
  MR_STANDING_WHOS_MY_LITTLE_STANDING_BOY,
  WHOS_MY_LITTLE_BABY_BIRD,
  WE_ARE_DRESSING_UP_AS_A_FAMILY_OF_SKELETONS,
  POOP_STUCK_TO_A_BUTT,
  WHEN_YOURE_DONE_WITH_YOUR_HAM_YOU_THROW_IT_ON_THE_GROUND,
  ONE_TWO_THREE_FOUR_FIVE_SIX_SEVEN_EIGHT_NINE_TEN,
  WERE_ALMOST_HOME,
  PUTTING_ON_YOUR_PANTS_LIKE_A_BIG_BOY,
  STREET_SWEEPER,
  MY_BABY_LOVES_TO_GO_POOPY,
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK,
  I_THINK_A_LOT_ABOUT_RINSING_THAT_COFFEE_POT,
  LETS_GO_PEE_WITH_DAD,
  BUBBLES_BUBBLES_WHOS_GOT_THE_BUBBLES,
  WASHING_YOUR_FACE,
  BYE_BYE_BUBBLES_BYE_BYE_BATHWATER,
  WHOS_MY_LITTLE_DAIKINI_BABY,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION,
  BABY_SKIN,
};
