#pragma once

const char MY_BABY_LOVES_TO_GO_POOPY_TITLE[] PROGMEM =
  "MY BABY\nLOVES TO GO\nPOOPY";
const char WASHING_YOUR_FACE_TITLE[] PROGMEM =
  "WASHING\nYOUR FACE";
const char WHOS_MY_LITTLE_BABY_BIRD_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE BABY\nBIRD";
const char ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE[] PROGMEM =
  "ANY KIND OF\nCAR AND ANY\nKIND OF TRUCK";
const char WHOS_MY_LITTLE_DAIKINI_BABY_TITLE[] PROGMEM =
  "WHO'S MY\nLITTLE DAIKINI\nBABY";
const char THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE[] PROGMEM =
  "THIS TOWN'S\nGOT A LOT OF\nCONSTRUCTION";
const char WERE_ALMOST_HOME_TITLE[] PROGMEM = "WE'RE ALMOST\nHOME";

// NOTE: must be alphabetically ordered like lengths and scores
const char * const SONG_TITLES[] PROGMEM = {
  ANY_KIND_OF_CAR_AND_ANY_KIND_OF_TRUCK_TITLE,
  MY_BABY_LOVES_TO_GO_POOPY_TITLE,
  THIS_TOWNS_GOT_A_LOT_OF_CONSTRUCTION_TITLE,
  WASHING_YOUR_FACE_TITLE,
  WERE_ALMOST_HOME_TITLE,
  WHOS_MY_LITTLE_BABY_BIRD_TITLE,
  WHOS_MY_LITTLE_DAIKINI_BABY_TITLE,
};
